services:
  apache-citas:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
    restart: always

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db6h0aovgdau0i
      MYSQL_USER: ujjvh6bdg2gyn
      MYSQL_PASSWORD: '1~l3}1Ke2^d$'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: